theme: jekyll-theme-modernist
title: Citi Bikes of NYC
description: We will analyze the trip data and station data of the Citi Bikes for an year from 05/01/2017 to 4/30/2018 and listen to the story taht the data tells us
